runtime: nodejs12
env: standard
instance_class: F1
handlers:
  - url: /(.*\..+)$
    static_files: dist/angular-chat-socketio/\1
    require_matching_file: false
    upload: dist/angular-chat-socketio/(.*\..+)$
  - url: /.*
    static_files: dist/angular-chat-socketio/index.html
    require_matching_file: false
    upload: dist/angular-chat-socketio/index.html
